begin;
select plan(31);

create temporary table package03_state (label text primary key, batch_id uuid, validation_run_id uuid, resolution_run_id uuid, manual_resolution_id uuid, old_family_id uuid, new_family_id uuid);
insert into auth.users (id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
values ('cccccccc-cccc-4ccc-8ccc-cccccccccccc','authenticated','authenticated','package03-anonymous@example.test','not-a-real-password',now(),'{}','{}',now(),now());
select set_config('request.jwt.claim.sub','cccccccc-cccc-4ccc-8ccc-cccccccccccc',true);
insert into public.app_user_capabilities(user_id,capability)
select 'cccccccc-cccc-4ccc-8ccc-cccccccccccc', capability from unnest(array['import.view','import.create','import.validate','import.publish','import.audit','product.view','product.audit','product.resolve','product.publish']) capability;

select ok(exists(select 1 from public.source_contract_versions where source_kind='PACKAGE_CONVERSION_HISTORY' and publication_mode='UPSERT_VERSIONED'),'package conversion source contract is versioned rather than a stock movement');
insert into package03_state(label,batch_id)
select 'first',(public.initiate_import_batch('PACKAGE_CONVERSION_HISTORY','anonymous-package.xlsx',64,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',repeat('a',64),'{}'::jsonb,'PACKAGE_CONVERSION_HISTORY:anonymous','package03-init',repeat('b',64))->>'batchId')::uuid;
select public.complete_import_upload((select batch_id from package03_state where label='first'),repeat('a',64),64);
select public.parse_package_conversion_batch((select batch_id from package03_state where label='first'),jsonb_build_array(
  jsonb_build_object('sheetName','Paket','sourceRowNumber',2,'rawCells','{"B2":{"rawValue":"2025-01-01"}}'::jsonb,'rowHash',repeat('1',64),'naturalKeyHash',repeat('2',64),'parsedPayload','{"operationDate":"2025-01-01","sourceMaterialCode":"A100","sourceQuantity":"5","targetMaterialCode":"A100_6","targetQuantity":"20","sourceDocumentReference":"ANON-1"}'::jsonb,'parserWarnings','[]'::jsonb),
  jsonb_build_object('sheetName','Paket','sourceRowNumber',3,'rawCells','{"B3":{"rawValue":"2025-01-02"}}'::jsonb,'rowHash',repeat('3',64),'naturalKeyHash',repeat('4',64),'parsedPayload','{"operationDate":"2025-01-02","sourceMaterialCode":"A100","sourceQuantity":"5","targetMaterialCode":"A100_12","targetQuantity":"10","sourceDocumentReference":"ANON-2"}'::jsonb,'parserWarnings','[]'::jsonb)
),'package-conversion-v2/1.0.0');
select is((select count(*)::integer from public.package_conversion_observations where import_batch_id=(select batch_id from package03_state where label='first')),2,'raw conversion observations remain immutable and separate from variants');
select is((public.validate_package_conversion_batch((select batch_id from package03_state where label='first'))->>'status'),'VALIDATED','positive dated non-self conversion rows validate');
update package03_state set validation_run_id=(select active_validation_run_id from public.import_batches where id=batch_id) where label='first';
select is((public.publish_package_conversion_batch((select batch_id from package03_state where label='first'),(select validation_run_id from package03_state where label='first'),0,'package03-publish',repeat('5',64))->>'status'),'PUBLISHED','valid package conversion batch publishes atomically');
update package03_state set resolution_run_id=(select id from public.product_resolution_runs where import_batch_id=batch_id) where label='first';
select is((select count(*)::integer from public.product_variants),3,'each code remains an independent product variant');
select is((select count(*)::integer from public.product_families),1,'consistent conversion component becomes one candidate product family');
select is((select count(*)::integer from public.package_conversion_edge_versions),2,'ratio evidence becomes directional product conversion edges');
select is((select target_units_per_source_unit from public.package_conversion_edge_versions order by target_units_per_source_unit desc limit 1),4::numeric,'exact conversion ratio is numeric not float');
select is((select count(*)::integer from public.product_resolution_issues where issue_code='MISSING_LITRE_ANCHOR'),3,'graph without an absolute anchor has explicit litre coverage issues');
select is((public.product_variants_list_v2(null,null,null,'2025-01-15T00:00:00Z',1,50)->'items'->0->>'materialCode'),'A100','product public read is deterministic and uses material codes without raw provenance');
select is((public.product_litre_coverage_v2('2025-01-15T00:00:00Z')->>'withOfficialLitreCount')::integer,0,'package graph does not invent an official litre coefficient');
select ok(not exists(select 1 from public.current_stock_imports),'Package 03 product publish creates no active-stock import or metric');
select throws_ok($$update public.package_conversion_edge_versions set evidence_count=2$$,'55000','PRODUCT_HISTORY_IMMUTABLE','conversion edge history cannot be overwritten');
select is(has_table_privilege('anon','public.product_variants','select'),false,'anonymous role cannot read product identities');
select is((public.product_resolution_reconciliation_v2((select resolution_run_id from package03_state where label='first'))->>'runId')::uuid,(select resolution_run_id from package03_state where label='first'),'audit reconciliation returns its exact immutable run');
delete from public.app_user_capabilities where user_id='cccccccc-cccc-4ccc-8ccc-cccccccccccc' and capability='product.audit';
select throws_ok($$select public.product_resolution_reconciliation_v2((select resolution_run_id from package03_state where label='first'))$$,'42501','PRODUCT_CAPABILITY_REQUIRED','product reconciliation fails closed when audit capability is removed');
insert into public.product_litre_versions(product_variant_id,litres_per_stock_unit,volume_tracked,valid_from,selection_reason,evidence)
select product_variant_id,20,true,now()-interval '10 days','ANONYMOUS_TEST_ANCHOR','[]'::jsonb from public.product_variants where material_code='A100';
select is((public.product_variants_list_v2(null,null,null,(now()-interval '2 days')::text::timestamptz,1,50)->'items'->0->>'litresPerStockUnit'),'20','an earlier asOf keeps its official litre version before a later decision');
select is((public.product_resolution_preview_v2((select id from public.product_resolution_issues where product_variant_id=(select product_variant_id from public.product_variants where material_code='A100') and state='OPEN' limit 1),jsonb_build_object('resolutionKind','NON_VOLUME','productVariantId',(select product_variant_id from public.product_variants where material_code='A100'),'validFrom',(now()-interval '1 day')::text))->>'requiresBackdatedApproval')::boolean,true,'backdated manual product decisions require explicit approval at preview');
select throws_ok($$select public.commit_product_resolution_v2((select id from public.product_resolution_issues where product_variant_id=(select product_variant_id from public.product_variants where material_code='A100') and state='OPEN' limit 1),jsonb_build_object('resolutionKind','NON_VOLUME','productVariantId',(select product_variant_id from public.product_variants where material_code='A100'),'validFrom',(now()-interval '1 day')::text),'anonymous non-volume decision')$$,'22023','BACKDATED_PRODUCT_RULE_REVIEW','a backdated product decision cannot commit without approval');
update package03_state set manual_resolution_id=(select (public.commit_product_resolution_v2((select id from public.product_resolution_issues where product_variant_id=(select product_variant_id from public.product_variants where material_code='A100') and state='OPEN' limit 1),jsonb_build_object('resolutionKind','NON_VOLUME','productVariantId',(select product_variant_id from public.product_variants where material_code='A100'),'validFrom',(now()-interval '1 day')::text,'backdatedApproval',true),'anonymous approved non-volume decision')->>'resolutionId')::uuid) where label='first';
select is((select volume_tracked from public.product_litre_versions where id=(select (new_value->>'versionId')::uuid from public.product_manual_resolutions where id=(select manual_resolution_id from package03_state where label='first'))),false,'approved non-volume proposal creates a typed temporal litre version');
select is((public.product_variants_list_v2(null,null,null,(now()-interval '2 days')::text::timestamptz,1,50)->'items'->0->>'litresPerStockUnit'),'20','new non-volume version leaves the historical asOf coefficient unchanged');
select is((public.revert_product_resolution_v2((select manual_resolution_id from package03_state where label='first'),'anonymous correction')->>'status'),'REVERTED','reverting a product decision is explicit and audited');
select is((public.product_variants_list_v2(null,null,null,now(),1,50)->'items'->0->>'litresPerStockUnit'),'20','reverting non-volume restores a new forward litre history without overwriting the old row');
update package03_state set old_family_id=(select product_family_id from public.product_family_membership_versions where product_variant_id=(select product_variant_id from public.product_variants where material_code='A100') and valid_to is null) where label='first';
insert into public.product_families(display_name,creation_reason) values('Anonymous review family','ANONYMOUS_TEST');
update package03_state set new_family_id=(select product_family_id from public.product_families where display_name='Anonymous review family') where label='first';
insert into public.product_resolution_issues(product_resolution_run_id,product_variant_id,issue_code,details)
values((select resolution_run_id from package03_state where label='first'),(select product_variant_id from public.product_variants where material_code='A100_12'),'FAMILY_SPLIT_REVIEW','{}'::jsonb);
update package03_state set manual_resolution_id=(select (public.commit_product_resolution_v2((select id from public.product_resolution_issues where issue_code='FAMILY_SPLIT_REVIEW' and state='OPEN' limit 1),jsonb_build_object('resolutionKind','FAMILY_MEMBERSHIP','productVariantId',(select product_variant_id from public.product_variants where material_code='A100_12'),'productFamilyId',(select new_family_id from package03_state where label='first'),'validFrom',(now()-interval '1 day')::text,'backdatedApproval',true),'anonymous family split approval')->>'resolutionId')::uuid) where label='first';
select is((select product_family_id from public.product_family_membership_versions where product_variant_id=(select product_variant_id from public.product_variants where material_code='A100_12') and valid_to is null),(select new_family_id from package03_state where label='first'),'family membership approval creates a new temporal membership rather than rewriting a material code');
select is((select product_family_id from public.product_family_membership_versions where product_variant_id=(select product_variant_id from public.product_variants where material_code='A100_12') and valid_from<now()-interval '2 days' and valid_to>now()-interval '2 days'),(select old_family_id from package03_state where label='first'),'family membership retains the old family for a historical asOf');
select is((public.revert_product_resolution_v2((select manual_resolution_id from package03_state where label='first'),'anonymous family correction')->>'status'),'REVERTED','family membership reversion is a new audited temporal decision');
insert into public.product_resolution_issues(product_resolution_run_id,product_family_id,issue_code,details)
values((select resolution_run_id from package03_state where label='first'),(select old_family_id from package03_state where label='first'),'CANONICAL_VARIANT_MISSING','{}'::jsonb);
select is((public.commit_product_resolution_v2((select id from public.product_resolution_issues where issue_code='CANONICAL_VARIANT_MISSING' and state='OPEN' limit 1),jsonb_build_object('resolutionKind','FAMILY_POLICY','productFamilyId',(select old_family_id from package03_state where label='first'),'canonicalStockVariantId',(select product_variant_id from public.product_variants where material_code='A100'),'replenishmentVariantId',(select product_variant_id from public.product_variants where material_code='A100_6'),'validFrom',(now()-interval '1 day')::text,'backdatedApproval',true),'anonymous policy approval')->>'status'),'COMMITTED','canonical and replenishment roles come only from an explicit family policy decision');
insert into public.product_resolution_issues(product_resolution_run_id,product_variant_id,issue_code,details)
values((select resolution_run_id from package03_state where label='first'),(select product_variant_id from public.product_variants where material_code='A100_6'),'LITRE_SOURCE_CONFLICT','{}'::jsonb);
update package03_state set manual_resolution_id=(select (public.commit_product_resolution_v2((select id from public.product_resolution_issues where issue_code='LITRE_SOURCE_CONFLICT' and state='OPEN' limit 1),jsonb_build_object('resolutionKind','LITRE_OVERRIDE','productVariantId',(select product_variant_id from public.product_variants where material_code='A100_6'),'litresPerStockUnit','5','evidence',jsonb_build_array(jsonb_build_object('kind','MANUAL_APPROVED','reference','anonymous')),'validFrom',(now()-interval '1 day')::text,'backdatedApproval',true),'anonymous litre override')->>'resolutionId')::uuid) where label='first';
select is((select litres_per_stock_unit from public.product_litre_versions where id=(select (new_value->>'versionId')::uuid from public.product_manual_resolutions where id=(select manual_resolution_id from package03_state where label='first'))),5::numeric,'litre override persists a canonical decimal rather than a float');
select is((public.revert_product_resolution_v2((select manual_resolution_id from package03_state where label='first'),'anonymous litre correction')->>'status'),'REVERTED','litre override can be reverted without deleting source evidence');
select throws_ok($$insert into public.product_litre_versions(product_variant_id,litres_per_stock_unit,volume_tracked,valid_from,selection_reason,evidence) select product_variant_id,20,true,now()+interval '1 second','OVERLAP_TEST','[]'::jsonb from public.product_variants where material_code='A100'$$,'23P01',null,'temporal exclusion prevents a second active official litre value');
insert into package03_state(label,batch_id)
select 'graph-conflict',(public.initiate_import_batch('PACKAGE_CONVERSION_HISTORY','anonymous-graph-conflict.xlsx',64,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',repeat('c',64),'{}'::jsonb,'PACKAGE_CONVERSION_HISTORY:anonymous-graph-conflict','package03-graph-init',repeat('d',64))->>'batchId')::uuid;
select public.complete_import_upload((select batch_id from package03_state where label='graph-conflict'),repeat('c',64),64);
select public.parse_package_conversion_batch((select batch_id from package03_state where label='graph-conflict'),jsonb_build_array(jsonb_build_object('sheetName','Paket','sourceRowNumber',2,'rawCells','{}'::jsonb,'rowHash',repeat('e',64),'naturalKeyHash',repeat('f',64),'parsedPayload','{"operationDate":"2025-01-03","sourceMaterialCode":"C100","sourceQuantity":"1","targetMaterialCode":"C100_6","targetQuantity":"6"}'::jsonb,'parserWarnings','[]'::jsonb)),'package-conversion-v2/1.0.0');
select throws_ok($$select public.validate_package_conversion_batch((select batch_id from package03_state where label='graph-conflict'),null,jsonb_build_array(jsonb_build_object('code','CONVERSION_CYCLE_INCONSISTENT','componentStart','C100')))$$,'P0001','PACKAGE_CONVERSION_VALIDATION_FAILED','graph conflict payload becomes a blocking database validation issue before publication');
select * from finish();
rollback;
