const fs = require('fs');
const noops = `
const loadCustomers = async () => [];
const loadAllSalesInvoices = async () => [];
const loadAllCollections = async () => [];
const loadAllCreditNotes = async () => [];
const loadAllPurchaseInvoices = async () => [];
const archiveCustomers = async (x) => ({});
const archiveSalesInvoices = async (x) => ({});
const archiveCollections = async (x) => ({});
const archivePurchaseInvoices = async (x) => ({});
const archiveCreditNotes = async (x) => ({});
const archiveCheques = async (x) => ({});
const deleteSalesInvoiceRecord = async (x) => {};
const deleteCollectionRecord = async (x) => {};
const deleteCreditNoteRecord = async (x) => {};
const deleteChequeRecord = async (x) => {};
const loadAllCheques = async () => [];
const updateChequesInArchive = async (x) => {};
const addUploadLogEntry = async (x) => {};
const clearAllArchive = async () => {};
const archiveShipmentBelgeler = async (x) => ({});
const archiveShipmentSiparisler = async (x) => ({});
const archiveSelloutData = async (x) => ({});
const loadAllShipmentBelgeler = async () => [];
const loadAllShipmentSiparisler = async () => [];
const loadAllSelloutData = async () => [];
`;
let content = fs.readFileSync('panel/src/services/customerService.ts', 'utf-8');
content = content.replace("import { safeIsoDate } from '../utils/dateUtils';", "import { safeIsoDate } from '../utils/dateUtils';" + noops);
fs.writeFileSync('panel/src/services/customerService.ts', content);
