import { inflateRawSync } from 'node:zlib';
import { SELLOUT_PARSER_VERSION,SelloutContractError,cleanText,headersMatch,canonicalDecimal,canonicalDate,sha256,headerText } from './selloutContract.js';
const fail=(code,details={})=>{throw new SelloutContractError(code,`sellout.parser.${code.toLowerCase()}`,details);};
const attr=(value,name)=>new RegExp(`(?:^|\\s)${name}="([^"]*)"`,'u').exec(value)?.[1]??null;
const decode=(value='')=>value.replace(/&#x([0-9a-f]+);/giu,(_m,n)=>String.fromCodePoint(Number.parseInt(n,16))).replace(/&#(\d+);/gu,(_m,n)=>String.fromCodePoint(Number(n))).replace(/&amp;/gu,'&').replace(/&lt;/gu,'<').replace(/&gt;/gu,'>').replace(/&quot;/gu,'"');
function files(buffer){if(!Buffer.isBuffer(buffer)||buffer.length===0||buffer.length>25*1024*1024)fail('XLSX_ARCHIVE_SIZE_REJECTED');let e=-1;for(let i=buffer.length-22;i>=Math.max(0,buffer.length-65557);i-=1)if(buffer.readUInt32LE(i)===0x06054b50){e=i;break;}if(e<0)fail('INVALID_XLSX_ARCHIVE');let offset=buffer.readUInt32LE(e+16);const count=buffer.readUInt16LE(e+10),result=new Map();if(count>200)fail('XLSX_ARCHIVE_STRUCTURE_REJECTED');for(let i=0;i<count;i+=1){if(buffer.readUInt32LE(offset)!==0x02014b50)fail('XLSX_ARCHIVE_STRUCTURE_REJECTED');const method=buffer.readUInt16LE(offset+10),size=buffer.readUInt32LE(offset+20),nl=buffer.readUInt16LE(offset+28),xl=buffer.readUInt16LE(offset+30),cl=buffer.readUInt16LE(offset+32),local=buffer.readUInt32LE(offset+42),name=buffer.subarray(offset+46,offset+46+nl).toString('utf8'),start=local+30+buffer.readUInt16LE(local+26)+buffer.readUInt16LE(local+28);if(!name||name.includes('..')||start+size>buffer.length||![0,8].includes(method))fail('XLSX_ARCHIVE_STRUCTURE_REJECTED');result.set(name,(method===0?buffer.subarray(start,start+size):inflateRawSync(buffer.subarray(start,start+size),{maxOutputLength:40*1024*1024})).toString('utf8'));offset+=46+nl+xl+cl;}return result;}
function sheets(entries){const workbook=entries.get('xl/workbook.xml'),rels=entries.get('xl/_rels/workbook.xml.rels');if(!workbook||!rels)fail('XLSX_WORKBOOK_NOT_FOUND');const relation=new Map([...rels.matchAll(/<Relationship\b([^>]*)\/?>(?:<\/Relationship>)?/gu)].map(m=>[attr(m[1],'Id'),attr(m[1],'Target')]));return [...workbook.matchAll(/<sheet\b([^>]*)\/?>(?:<\/sheet>)?/gu)].map(m=>({name:decode(attr(m[1],'name')??''),hidden:['hidden','veryHidden'].includes(attr(m[1],'state')),path:`xl/${(relation.get(attr(m[1],'r:id'))??'').replace(/^\.\//u,'')}`})).filter(s=>s.name&&entries.has(s.path));}
function readCells(xml,shared){const result=new Map();for(const row of xml.matchAll(/<row\b([^>]*)>([\s\S]*?)<\/row>/gu)){const n=Number(attr(row[1],'r'));for(const cell of row[2].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/gu)){const a=attr(cell[1],'r'),t=attr(cell[1],'t'),raw=/<v\b[^>]*>([\s\S]*?)<\/v>/u.exec(cell[2])?.[1]??/<t\b[^>]*>([\s\S]*?)<\/t>/u.exec(cell[2])?.[1]??'';if(a)result.set(a,{rawValue:t==='s'?shared[Number(raw)]??'':decode(raw),sourceType:t==='s'||t==='inlineStr'?'text':'number',rowNumber:n});}}return result;}
const column=(a)=>a.replace(/[0-9]+$/u,'');
const excelDate=(value)=>{if(!/^\d+(?:\.0+)?$/u.test(value))return null;const date=new Date(Date.UTC(1899,11,30)+Number(value)*86400000);return Number.isNaN(date.valueOf())?null:date.toISOString().slice(0,10);};
export function parseSelloutWorkbook(buffer){const entries=files(buffer),shared=[...(entries.get('xl/sharedStrings.xml')??'').matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/gu)].map(m=>[...m[1].matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/gu)].map(x=>decode(x[1])).join('')),candidates=sheets(entries).map(s=>({...s,cells:readCells(entries.get(s.path),shared)})).filter(s=>headersMatch([...s.cells].filter(([a])=>/1$/u.test(a)).map(([,v])=>v.rawValue)));if(candidates.length===0)fail('SELLOUT_SHEET_NOT_FOUND');if(candidates.length>1||candidates[0].hidden)fail('AMBIGUOUS_SELLOUT_SHEET');const sheet=candidates[0],headers=new Map([...sheet.cells].filter(([a])=>/1$/u.test(a)).map(([a,v])=>[headerText(v.rawValue),column(a)])),byRow=new Map();for(const[a,c]of sheet.cells){if(c.rowNumber<=1)continue;const row=byRow.get(c.rowNumber)??{};row[column(a)]=c;byRow.set(c.rowNumber,row);}const records=[],occurrence=new Map();for(const[rowNumber,row]of byRow){const cell=(name)=>row[headers.get(headerText(name))],documentNo=cleanText(cell('Satış Belgesi')?.rawValue),customerCode=cleanText(cell('Müşteri No')?.rawValue),materialCode=cleanText(cell('Malzeme Kodu')?.rawValue),quantity=canonicalDecimal(cell('Miktar')?.rawValue),litres=canonicalDecimal(cell('Litre')?.rawValue),billingDate=canonicalDate(cell('Faturalama Tarihi')?.rawValue)??excelDate(cell('Faturalama Tarihi')?.rawValue??'');if([documentNo,customerCode,materialCode,quantity,litres,billingDate].every(v=>!v))continue;const signature=sha256({customerCode,documentNo,billingDate,materialCode,quantity,litres,movementEvidence:null}),ordinal=(occurrence.get(signature)??0)+1;occurrence.set(signature,ordinal);records.push(Object.freeze({sheetName:sheet.name,sourceRowNumber:rowNumber,documentNo,customerCode,materialCode,materialName:cleanText(cell('Malzeme Tnm.')?.rawValue)??cleanText(cell('Malzeme Tanımı')?.rawValue),quantity,litres,billingDate,movementEvidence:null,rawPayload:Object.freeze({net:cleanText(cell('Net')?.rawValue),gross:cleanText(cell('Brüt')?.rawValue),discount:cleanText(cell('Toplam İskonto')?.rawValue),rawChannel:cleanText(cell('Satış Kanalı Tnm.')?.rawValue)??cleanText(cell('Müşteri Kanalı Tnm.')?.rawValue),rawRep:cleanText(cell('Satış Temsilcisi Adı')?.rawValue)}),rowSignature:signature,occurrenceOrdinal:ordinal,warnings:Object.freeze([])}));}return Object.freeze({parserVersion:SELLOUT_PARSER_VERSION,records:Object.freeze(records)});}
