-- Package 04: capability-gated read models and target mutations.
create or replace view public.sellout_monthly_performance_v with (security_invoker=true) as
select to_char(e.billing_date,'YYYY-MM') period_key,r.rep_person_id,r.ssm_person_id,r.channel,
 sum(e.litres) filter(where v.movement_type='POSITIVE_SALE' and v.included_in_official_net) gross_litres,
 sum(abs(e.litres)) filter(where v.movement_type='PRODUCT_RETURN' and v.included_in_official_net) return_litres,
 sum(case when v.movement_type='POSITIVE_SALE' then e.litres when v.movement_type in ('PRODUCT_RETURN','CANCEL_REVERSAL') then -abs(e.litres) else 0 end) filter(where v.included_in_official_net) net_litres
from public.sellout_line_events e join public.sellout_line_event_versions v on v.sellout_line_event_id=e.id and v.is_current join public.sellout_responsibility_components r on r.sellout_line_event_id=e.id where r.customer_status='ACTIVE' group by 1,2,3,4;

create or replace function public.sellout_periods_v2() returns jsonb language plpgsql security definer set search_path='' as $$
begin perform public.require_sellout_capability('sellout.view'); return jsonb_build_object('items',(select coalesce(jsonb_agg(jsonb_build_object('periodKey',p,'year',substring(p,1,4)::int,'month',substring(p,6,2)::int,'displayLabel',to_char((p||'-01')::date,'YYYY TMMonth'),'firstBillingDate',mn,'lastBillingDate',mx,'coverageState',coverage) order by p),'[]'::jsonb) from(select to_char(e.billing_date,'YYYY-MM')p,min(e.billing_date)mn,max(e.billing_date)mx,case when bool_or(e.movement_type='UNCLASSIFIED_NEGATIVE') then 'PARTIAL_CLASSIFICATION' else 'COMPLETE' end coverage from public.sellout_line_events e group by 1)s)); end; $$;
create or replace function public.sellout_monthly_performance_v2(p_month text,p_as_of date default current_date,p_scope_type text default 'COMPANY',p_scope_id uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_gross numeric;v_returns numeric;v_net numeric;v_target numeric;v_run uuid;
begin
 perform public.require_sellout_capability('sellout.view'); if p_month !~ '^[0-9]{4}-(0[1-9]|1[0-2])$' then raise exception 'INVALID_SELLOUT_MONTH' using errcode='22023'; end if;
 select coalesce(sum(gross_litres),0),coalesce(sum(return_litres),0),coalesce(sum(net_litres),0) into v_gross,v_returns,v_net from public.sellout_monthly_performance_v where period_key=p_month and(p_scope_type='COMPANY' or(p_scope_type='REP' and rep_person_id=p_scope_id)or(p_scope_type='SSM' and ssm_person_id=p_scope_id));
 select sum(target_litres) into v_target from public.sellout_target_versions where period_key=p_month and reversed_at is null and(p_scope_type='COMPANY' or(p_scope_type='REP' and rep_person_id=p_scope_id)or(p_scope_type='SSM' and exists(select 1 from public.rep_ssm_assignments a where a.id=owner_ssm_assignment_id and a.ssm_person_id=p_scope_id)));
 select id into v_run from public.sellout_calculation_runs where period_key=p_month order by created_at desc limit 1;
 return jsonb_build_object('period',p_month,'asOfDate',p_as_of,'scope',jsonb_build_object('type',p_scope_type,'id',p_scope_id),'grossLitres',public.product_canonical_decimal_text_v2(v_gross),'returnLitres',public.product_canonical_decimal_text_v2(v_returns),'reversalLitres','0','netLitres',public.product_canonical_decimal_text_v2(v_net),'targetLitres',public.product_canonical_decimal_text_v2(v_target),'attainment',case when v_target is null or v_target=0 then null else public.product_canonical_decimal_text_v2(v_net/v_target) end,'remaining',case when v_target is null then null else public.product_canonical_decimal_text_v2(greatest(0,v_target-v_net)) end,'overTarget',case when v_target is null then null else public.product_canonical_decimal_text_v2(greatest(0,v_net-v_target)) end,'calculationRunId',v_run,'financialEffect','NONE');
end; $$;
create or replace function public.sellout_events_v2(p_from date,p_to date,p_customer_id uuid default null,p_document_no text default null,p_variant_id uuid default null,p_family_id uuid default null,p_movement_type text default null,p_page int default 1,p_page_size int default 50) returns jsonb language plpgsql security definer set search_path='' as $$
begin perform public.require_sellout_capability('sellout.view'); if p_page<1 or p_page_size<1 or p_page_size>100 then raise exception 'INVALID_PAGINATION' using errcode='22023'; end if; return jsonb_build_object('items',(select coalesce(jsonb_agg(jsonb_build_object('eventId',id,'billingDate',billing_date,'documentNo',document_no,'customerId',customer_id,'variantId',product_variant_id,'familyId',product_family_id,'quantity',public.product_canonical_decimal_text_v2(quantity),'litres',public.product_canonical_decimal_text_v2(litres),'movementType',movement_type)order by billing_date,id),'[]'::jsonb)from(select e.*,o.document_no from public.sellout_line_events e join public.sellout_line_observations o on o.id=e.observation_id where e.billing_date between p_from and p_to and(p_customer_id is null or e.customer_id=p_customer_id)and(p_document_no is null or o.document_no=p_document_no)and(p_variant_id is null or e.product_variant_id=p_variant_id)and(p_family_id is null or e.product_family_id=p_family_id)and(p_movement_type is null or e.movement_type::text=p_movement_type)order by e.billing_date,e.id offset(p_page-1)*p_page_size limit p_page_size)x),'page',p_page,'pageSize',p_page_size); end; $$;
create or replace function public.sellout_reconciliation_v2(p_month text,p_scope_type text default 'COMPANY',p_scope_id uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$ begin perform public.require_sellout_capability('sellout.audit'); return jsonb_build_object('period',p_month,'performance',public.sellout_monthly_performance_v2(p_month,current_date,p_scope_type,p_scope_id),'unclassifiedNegativeLitres',coalesce((select public.product_canonical_decimal_text_v2(sum(abs(litres))) from public.sellout_line_events where to_char(billing_date,'YYYY-MM')=p_month and movement_type='UNCLASSIFIED_NEGATIVE'),'0')); end; $$;
create or replace function public.sellout_targets_v2(p_month text,p_rep_id uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$ begin perform public.require_sellout_capability('sellout.target.view'); if p_month !~ '^[0-9]{4}-(0[1-9]|1[0-2])$' then raise exception 'INVALID_SELLOUT_MONTH' using errcode='22023'; end if; return jsonb_build_object('period',p_month,'items',(select coalesce(jsonb_agg(jsonb_build_object('targetVersionId',id,'repId',rep_person_id,'channel',channel,'targetLitres',public.product_canonical_decimal_text_v2(target_litres),'ownerSsmAssignmentId',owner_ssm_assignment_id,'createdAt',created_at)order by rep_person_id,channel),'[]'::jsonb)from public.sellout_target_versions where period_key=p_month and reversed_at is null and(p_rep_id is null or rep_person_id=p_rep_id))); end; $$;
create or replace function public.sellout_target_preview_v2(p_input jsonb) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_rep uuid;v_month text;v_channel public.sellout_target_channel;v_litres numeric;v_reason text;v_current uuid;v_hash text; begin perform public.require_sellout_capability('sellout.target.mutate'); v_rep=(p_input->>'repId')::uuid;v_month=p_input->>'periodKey';v_channel=(p_input->>'channel')::public.sellout_target_channel;v_litres=(p_input->>'targetLitres')::numeric;v_reason=btrim(coalesce(p_input->>'reason',''));if v_month !~ '^[0-9]{4}-(0[1-9]|1[0-2])$' or v_litres<0 or v_reason='' then raise exception 'INVALID_TARGET_DRAFT' using errcode='22023';end if;select id into v_current from public.sellout_target_versions where rep_person_id=v_rep and period_key=v_month and channel=v_channel and reversed_at is null;v_hash=encode(extensions.digest(jsonb_build_object('repId',v_rep,'periodKey',v_month,'channel',v_channel,'targetLitres',v_litres,'reason',v_reason,'currentId',v_current)::text,'sha256'),'hex');return jsonb_build_object('previewHash',v_hash,'currentTargetVersionId',v_current,'proposedTargetLitres',public.product_canonical_decimal_text_v2(v_litres));end; $$;
create or replace function public.commit_sellout_target_v2(p_input jsonb,p_preview_hash text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_preview jsonb;v_new public.sellout_target_versions;v_old uuid; begin perform public.require_sellout_capability('sellout.target.mutate');v_preview=public.sellout_target_preview_v2(p_input);if v_preview->>'previewHash'<>p_preview_hash then raise exception 'STALE_TARGET_PREVIEW' using errcode='P0001';end if;v_old=nullif(v_preview->>'currentTargetVersionId','')::uuid;if v_old is not null then update public.sellout_target_versions set reversed_at=now(),reversed_by=auth.uid() where id=v_old;end if;insert into public.sellout_target_versions(rep_person_id,period_key,channel,target_litres,owner_ssm_assignment_id,reason,created_by)values((p_input->>'repId')::uuid,p_input->>'periodKey',(p_input->>'channel')::public.sellout_target_channel,(p_input->>'targetLitres')::numeric,(select id from public.rep_ssm_assignments where rep_person_id=(p_input->>'repId')::uuid and valid_to is null order by valid_from desc limit 1),p_input->>'reason',auth.uid())returning * into v_new;return jsonb_build_object('targetVersionId',v_new.id,'status','COMMITTED','replacedTargetVersionId',v_old);end; $$;
create or replace function public.reverse_sellout_target_v2(p_target_version_id uuid,p_reason text) returns jsonb language plpgsql security definer set search_path='' as $$ begin perform public.require_sellout_capability('sellout.target.mutate');if btrim(coalesce(p_reason,''))='' then raise exception 'TARGET_REVERSE_REASON_REQUIRED' using errcode='22023';end if;update public.sellout_target_versions set reversed_at=now(),reversed_by=auth.uid() where id=p_target_version_id and reversed_at is null;if not found then raise exception 'TARGET_VERSION_NOT_REVERSIBLE' using errcode='P0001';end if;return jsonb_build_object('targetVersionId',p_target_version_id,'status','REVERSED','reason',p_reason);end; $$;
create or replace function public.sellout_exceptions_v2(p_batch_id uuid default null,p_month text default null,p_code text default null,p_page int default 1,p_page_size int default 50) returns jsonb language plpgsql security definer set search_path='' as $$ begin perform public.require_sellout_capability('sellout.audit');if p_page<1 or p_page_size<1 or p_page_size>100 then raise exception 'INVALID_PAGINATION' using errcode='22023';end if;return jsonb_build_object('items',(select coalesce(jsonb_agg(jsonb_build_object('issueId',i.id,'code',i.message_key,'severity',i.severity,'details',i.details)order by i.created_at,i.id),'[]'::jsonb)from(select i.*from public.data_quality_issues i join public.validation_runs r on r.id=i.validation_run_id join public.import_batches b on b.id=r.import_batch_id where b.source_kind='SELLOUT_TRADITIONAL'and(p_batch_id is null or b.id=p_batch_id)and(p_code is null or i.message_key=p_code)order by i.created_at,i.id offset(p_page-1)*p_page_size limit p_page_size)i),'page',p_page,'pageSize',p_page_size,'month',p_month);end; $$;
create or replace function public.sellout_resolution_preview_v2(p_input jsonb) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_event public.sellout_line_events;v_current public.sellout_line_event_versions;v_movement public.sellout_movement_type;v_reason text;v_original uuid;v_hash text; begin perform public.require_sellout_capability('sellout.resolve');select * into v_event from public.sellout_line_events where id=(p_input->>'selloutLineEventId')::uuid;if not found then raise exception 'SELLOUT_EVENT_NOT_FOUND' using errcode='P0002';end if;select * into v_current from public.sellout_line_event_versions where sellout_line_event_id=v_event.id and is_current for update;v_movement=(p_input->>'movementType')::public.sellout_movement_type;v_reason=btrim(coalesce(p_input->>'reason',''));v_original=nullif(p_input->>'originalLineEventId','')::uuid;if v_reason='' or v_movement in ('INVALID','POSITIVE_SALE') then raise exception 'INVALID_SELL_OUT_RESOLUTION' using errcode='22023';end if;if v_movement='CANCEL_REVERSAL' and (v_original is null or not exists(select 1 from public.sellout_line_events where id=v_original and customer_id=v_event.customer_id and id<>v_event.id)) then raise exception 'CANCEL_REVERSAL_EVIDENCE_REQUIRED' using errcode='22023';end if;if nullif(p_input->>'expectedVersionId','')::uuid is distinct from v_current.id then raise exception 'STALE_SELL_OUT_EVENT_VERSION' using errcode='P0001';end if;v_hash=encode(extensions.digest(jsonb_build_object('eventId',v_event.id,'expectedVersionId',v_current.id,'movementType',v_movement,'reason',v_reason,'originalLineEventId',v_original)::text,'sha256'),'hex');return jsonb_build_object('previewHash',v_hash,'eventId',v_event.id,'currentVersionId',v_current.id,'proposedMovementType',v_movement,'financialEffect','NONE','stockEffect','NONE');end; $$;
create or replace function public.commit_sellout_resolution_v2(p_input jsonb,p_preview_hash text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_preview jsonb;v_current public.sellout_line_event_versions;v_resolution public.sellout_manual_resolutions;v_new public.sellout_line_event_versions;v_movement public.sellout_movement_type;v_event uuid;v_original uuid; begin perform public.require_sellout_capability('sellout.resolve');v_preview=public.sellout_resolution_preview_v2(p_input);if v_preview->>'previewHash'<>p_preview_hash then raise exception 'STALE_SELL_OUT_RESOLUTION_PREVIEW' using errcode='P0001';end if;v_event=(p_input->>'selloutLineEventId')::uuid;select * into v_current from public.sellout_line_event_versions where id=(v_preview->>'currentVersionId')::uuid for update;v_movement=(p_input->>'movementType')::public.sellout_movement_type;v_original=nullif(p_input->>'originalLineEventId','')::uuid;insert into public.sellout_manual_resolutions(sellout_line_event_id,requested_movement_type,reason,expected_event_version,preview_hash,committed_at,actor_id) values(v_event,v_movement,p_input->>'reason',v_current.created_at,p_preview_hash,now(),auth.uid())returning * into v_resolution;update public.sellout_line_event_versions set is_current=false where id=v_current.id;insert into public.sellout_line_event_versions(sellout_line_event_id,version_no,movement_type,included_in_official_net,prior_version_id,manual_resolution_id,original_line_event_id,is_current,created_by)values(v_event,v_current.version_no+1,v_movement,v_movement in ('PRODUCT_RETURN','CANCEL_REVERSAL'),v_current.id,v_resolution.id,v_original,true,auth.uid())returning * into v_new;insert into public.sellout_calculation_runs(period_key,as_of_date,source_version_set,status)select to_char(billing_date,'YYYY-MM'),current_date,jsonb_build_object('manualResolutionId',v_resolution.id,'eventVersionId',v_new.id),'PUBLISHED' from public.sellout_line_events where id=v_event;return jsonb_build_object('resolutionId',v_resolution.id,'eventVersionId',v_new.id,'status','COMMITTED');end; $$;
create or replace function public.reverse_sellout_resolution_v2(p_resolution_id uuid,p_reason text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_resolution public.sellout_manual_resolutions;v_version public.sellout_line_event_versions; begin perform public.require_sellout_capability('sellout.resolve');if btrim(coalesce(p_reason,''))='' then raise exception 'RESOLUTION_REVERSE_REASON_REQUIRED' using errcode='22023';end if;select * into v_resolution from public.sellout_manual_resolutions where id=p_resolution_id and committed_at is not null and reversed_at is null for update;if not found then raise exception 'RESOLUTION_NOT_REVERSIBLE' using errcode='P0001';end if;select * into v_version from public.sellout_line_event_versions where manual_resolution_id=p_resolution_id and is_current for update;if not found then raise exception 'RESOLUTION_VERSION_NOT_CURRENT' using errcode='P0001';end if;update public.sellout_line_event_versions set is_current=false where id=v_version.id;update public.sellout_line_event_versions set is_current=true where id=v_version.prior_version_id;update public.sellout_manual_resolutions set reversed_at=now() where id=p_resolution_id;insert into public.sellout_calculation_runs(period_key,as_of_date,source_version_set,status)select to_char(billing_date,'YYYY-MM'),current_date,jsonb_build_object('reversedResolutionId',p_resolution_id,'reason',p_reason),'PUBLISHED' from public.sellout_line_events where id=v_resolution.sellout_line_event_id;return jsonb_build_object('resolutionId',p_resolution_id,'status','REVERSED');end; $$;

do $$ declare t text; begin foreach t in array array['sellout_imports','sellout_staging_rows','sellout_line_observations','sellout_document_events','sellout_line_events','sellout_line_event_versions','sellout_responsibility_components','sellout_coverage_days','sellout_classification_runs','sellout_classification_issues','sellout_manual_resolutions','sellout_target_versions','sellout_calculation_runs'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on table public.%I from anon, authenticated',t); end loop; end $$;
grant select on public.sellout_monthly_performance_v to authenticated;
create policy sellout_events_view on public.sellout_line_events for select to authenticated using(public.has_capability(auth.uid(),'sellout.view'));
create policy sellout_documents_view on public.sellout_document_events for select to authenticated using(public.has_capability(auth.uid(),'sellout.view'));
create policy sellout_responsibility_view on public.sellout_responsibility_components for select to authenticated using(public.has_capability(auth.uid(),'sellout.view'));
create policy sellout_event_versions_view on public.sellout_line_event_versions for select to authenticated using(public.has_capability(auth.uid(),'sellout.view'));
create policy sellout_targets_view on public.sellout_target_versions for select to authenticated using(public.has_capability(auth.uid(),'sellout.target.view'));
create policy sellout_audit_imports on public.sellout_imports for select to authenticated using(public.has_capability(auth.uid(),'sellout.audit'));
create policy sellout_audit_staging on public.sellout_staging_rows for select to authenticated using(public.has_capability(auth.uid(),'sellout.audit'));
create policy sellout_audit_observations on public.sellout_line_observations for select to authenticated using(public.has_capability(auth.uid(),'sellout.audit'));
revoke all on function public.require_sellout_capability(text),public.parse_sellout_batch(uuid,jsonb,text,text),public.validate_sellout_batch(uuid,text),public.publish_sellout_overlap(uuid,uuid,integer,text,text,text),public.sellout_periods_v2(),public.sellout_monthly_performance_v2(text,date,text,uuid),public.sellout_events_v2(date,date,uuid,text,uuid,uuid,text,int,int),public.sellout_reconciliation_v2(text,text,uuid),public.sellout_targets_v2(text,uuid),public.sellout_target_preview_v2(jsonb),public.commit_sellout_target_v2(jsonb,text),public.reverse_sellout_target_v2(uuid,text),public.sellout_exceptions_v2(uuid,text,text,int,int),public.sellout_resolution_preview_v2(jsonb),public.commit_sellout_resolution_v2(jsonb,text),public.reverse_sellout_resolution_v2(uuid,text) from public,anon;
grant execute on function public.parse_sellout_batch(uuid,jsonb,text,text),public.validate_sellout_batch(uuid,text),public.publish_sellout_overlap(uuid,uuid,integer,text,text,text),public.sellout_periods_v2(),public.sellout_monthly_performance_v2(text,date,text,uuid),public.sellout_events_v2(date,date,uuid,text,uuid,uuid,text,int,int),public.sellout_reconciliation_v2(text,text,uuid),public.sellout_targets_v2(text,uuid),public.sellout_target_preview_v2(jsonb),public.commit_sellout_target_v2(jsonb,text),public.reverse_sellout_target_v2(uuid,text),public.sellout_exceptions_v2(uuid,text,text,int,int),public.sellout_resolution_preview_v2(jsonb),public.commit_sellout_resolution_v2(jsonb,text),public.reverse_sellout_resolution_v2(uuid,text) to authenticated;
